sudo: required

branches:
  only:
  - svx

services:
  - docker

before_install:
  - ./scripts/changelog.sh
  - docker pull testthedocs/ttd-coala

script:
 - docker run -it --rm -v "${PWD}":/srv testthedocs/ttd-coala
