version: "2"
services:
  planet:
    image: abiosoft/caddy
    networks:
    - plone-net
    ports:
    - 2015:2015
    volumes:
    - ./Caddyfile-test:/etc/Caddyfile
    - ./index.html:/srv/index.html
    #depends_on:
    #- caddy

  caddy:
    image: testthedocs/ttd-caddy
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    ports:
    - 80:80
    networks:
    - plone-net

networks:
  plone-net:
    driver: bridge

