version: "2"
services:
  planet:
    image: plone/planet
    networks:
    - plone-net
    expose:
    - 2015

  caddy:
    image: testthedocs/ttd-caddy
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    ports:
    - 80:80
    networks:
    - plone-net

networks:
  plone-net:
    driver: bridge

